### ISSUE TITLE
Enabling navigation to login page after logout is done

### ISSUE THREAD

**Issue by mishrasur7** [haagahelia/siba-fe#204]
- Current implementation does not allow to navigate to login page straight after we logout. 
- Which ever page we are in before logout, even after logout we remain in the same page 
- **Better solution should be to enable smooth navigation to login page right after we logout**

**Comment by mal092** [comment]
Hello! I would like to work on this issue.

**Comment by mishrasur7** [comment]
Go ahead!

**Comment by Divyansh72144** [comment]
I did it :)
